### ISSUE TITLE
Chest log import - wrong date format

### ISSUE THREAD

**Issue by madvac** [matheussampaio/ao-loot-logger-viewer#4]
hello,

when i copy chest logs from client, date is in format:

MM-DD-YYYY

When i try to upload this file to web pages, it is uploaded in another format

DD-MM-YYYY

My windows  use DD-MM-YYYY format.

Thx.

**Comment by matheussampaio** [comment]
Sometimes it is impossible to guess correctly if a date is in MM-DD-YYYY or DD-MM-YYYY format. Things would be easier if Albion exported a standard format with locale and timezone, but it doesn't, so we have to guess.

There isn't much I can do to reliability fix this without causing problems for people with different locales.

Try to use a different language in the Albion client (one that uses DD-MM-YYYY) or fixing the format in the file itself.
